/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareEnv cloudflare-env.d.ts` (hash: 4c365f2068852031af6d39a18cdcf6a4)
interface __BaseEnv_CloudflareEnv {
	SOCIAL_MEDIA_KV: KVNamespace;
	DB: D1Database;
	ASSETS: Fetcher;
	META_APP_ID: "2566616200453545";
	APP_BASE_URL: "https://villa-yonetim.caglarmurat10.workers.dev";
	OPENAI_TEXT_MODEL: "gpt-5.6-terra";
	OPENAI_IMAGE_MODEL: "gpt-image-2";
	AI_IMAGE_ENABLED: "false";
	AI_VIDEO_ENABLED: "false";
	META_APP_SECRET: string;
	OPENAI_API_KEY: string;
	PEXELS_API_KEY: string;
	SOCIAL_AI_ADMIN_KEY: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker");
	}
	interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "META_APP_ID" | "APP_BASE_URL" | "OPENAI_TEXT_MODEL" | "OPENAI_IMAGE_MODEL" | "AI_IMAGE_ENABLED" | "AI_VIDEO_ENABLED" | "META_APP_SECRET" | "OPENAI_API_KEY" | "PEXELS_API_KEY" | "SOCIAL_AI_ADMIN_KEY">> {}
}
