/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareEnv cloudflare-env.d.ts` (hash: 0c71f5964f197ce4a33ac95e04fbd981)
interface __BaseEnv_CloudflareEnv {
	SOCIAL_MEDIA_KV: KVNamespace;
	DB: D1Database;
	ASSETS: Fetcher;
	META_APP_ID: "2566616200453545";
	APP_BASE_URL: "https://villa-yonetim.caglarmurat10.workers.dev";
	META_APP_SECRET: string;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "META_APP_ID" | "APP_BASE_URL" | "META_APP_SECRET">> {}
}
