"use client";

import { useEffect, useMemo, useState } from "react";
import Image from "next/image";
import type { Villa } from "@/lib/types";
import SocialNav from "./SocialNav";
import styles from "./SocialOperations.module.css";

type Account = { villa: Villa; followers: number | null; metrics: Record<string,number>; permission_status?: string; last_success_at?: string|null };
type State = { villa: Villa; permission_status: string; last_success_at: string|null; last_error:string|null };
type Media = { id:string; villa:Villa; media_type:string; published_at:string|null; caption_preview:string; thumbnail_url?:string|null; category?:string|null; metrics:Record<string,number> };
const metric=(values:Record<string,number>,...names:string[])=>names.map((name)=>values[name]).find((value)=>typeof value==="number")??null;

export default function SocialStatistics(){
  const [accounts,setAccounts]=useState<Account[]>([]);const[states,setStates]=useState<State[]>([]);const[media,setMedia]=useState<Media[]>([]);const[recommendations,setRecommendations]=useState<string[]>([]);const[notice,setNotice]=useState("");
  useEffect(()=>{let cancelled=false;void fetch("/api/social/insights").then(async(response)=>{const data=await response.json().catch(()=>({}));if(cancelled)return;if(response.ok){setAccounts(data.accounts??[]);setStates(data.states??[]);setMedia(data.media??[]);setRecommendations(data.recommendations??[]);}else setNotice(data.error??"İstatistikler yüklenemedi.");});return()=>{cancelled=true;};},[]);
  const top=useMemo(()=>[...media].sort((a,b)=>(metric(b.metrics,"reach","views","plays")??0)-(metric(a.metrics,"reach","views","plays")??0)).slice(0,10),[media]);
  const hours=useMemo(()=>{if(media.length<3)return[];const grouped=new Map<number,{total:number,count:number}>();for(const item of media){if(!item.published_at)continue;const hour=Number(new Intl.DateTimeFormat("en-GB",{timeZone:"Europe/Istanbul",hour:"2-digit",hourCycle:"h23"}).format(new Date(item.published_at)));const score=metric(item.metrics,"total_interactions","reach","views","plays");if(score===null)continue;const current=grouped.get(hour)??{total:0,count:0};current.total+=score;current.count+=1;grouped.set(hour,current);}return[...grouped.entries()].filter(([,value])=>value.count>=2).map(([hour,value])=>({hour,average:Math.round(value.total/value.count),count:value.count})).sort((a,b)=>b.average-a.average).slice(0,4);},[media]);
  const categories=useMemo(()=>{if(media.length<3)return[];const grouped=new Map<string,{total:number,count:number}>();for(const item of media){const score=metric(item.metrics,"reach","views","plays");if(score===null)continue;const name=item.category??item.media_type;const value=grouped.get(name)??{total:0,count:0};value.total+=score;value.count+=1;grouped.set(name,value);}return[...grouped.entries()].filter(([,value])=>value.count>=2).map(([name,value])=>({name,average:Math.round(value.total/value.count),count:value.count})).sort((a,b)=>b.average-a.average).slice(0,5);},[media]);
  return <main className={styles.page}><div className={styles.shell}><SocialNav/><section className={styles.hero}><div><span className={styles.eyebrow}>INSTAGRAM PERFORMANS</span><h1>Gerçek veriye dayalı istatistikler</h1><p>Meta’nın döndürdüğü metrikler gösterilir; eksik değerler tahmin edilmez.</p></div></section>{notice?<p className={styles.message}>{notice}</p>:null}
    <div className={styles.statCards}>{(["Destan","Safira"] as const).map((villa)=>{const account=accounts.find((item)=>item.villa===villa);const state=states.find((item)=>item.villa===villa);const needsAuth=(state?.permission_status??account?.permission_status)==="reauthorization_required";const villaMedia=media.filter((item)=>item.villa===villa);return <article className={styles.statCard} key={villa}><div className={styles.panelHead}><div><span className={styles.eyebrow}>VILLA {villa.toUpperCase()}</span><h2>Instagram özeti</h2></div></div>{needsAuth?<div className={styles.notice}>Insights izni için yeniden yetkilendirme gerekiyor. Mevcut yayın sistemi çalışmaya devam eder.<br/><a className={styles.primary} href={`/api/meta/instagram/connect?villa=${villa}`}>Yeniden yetkilendir</a></div>:null}<div className={styles.metrics}><div><span>Takipçi</span><strong>{account?.followers??"—"}</strong></div><div><span>Erişim</span><strong>{account?metric(account.metrics,"reach")??"—":"—"}</strong></div><div><span>Etkileşim</span><strong>{account?metric(account.metrics,"total_interactions","accounts_engaged")??"—":"—"}</strong></div><div><span>Yayın</span><strong>{villaMedia.length}</strong></div></div>{!account&&!needsAuth?<p className={styles.muted}>Henüz snapshot verisi yok. Cron güvenli senkron penceresinde veriyi alacak.</p>:null}</article>;})}</div>
    <section className={styles.panel}><div className={styles.panelHead}><div><span className={styles.eyebrow}>EN İYİ GÖNDERİLER</span><h2>Performansa göre sıralama</h2></div></div>{top.length?<div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>Medya</th><th>Villa</th><th>Tür</th><th>Tarih</th><th>Erişim/Görüntülenme</th><th>Beğeni</th><th>Yorum</th><th>Kaydetme</th><th>Paylaşım</th></tr></thead><tbody>{top.map((item)=><tr key={item.id}><td>{item.thumbnail_url?<Image unoptimized width={54} height={54} className={styles.thumb} src={item.thumbnail_url} alt=""/>:"—"}</td><td>{item.villa}</td><td>{item.media_type}</td><td>{item.published_at?new Intl.DateTimeFormat("tr-TR",{dateStyle:"short",timeStyle:"short",timeZone:"Europe/Istanbul"}).format(new Date(item.published_at)):"—"}</td><td>{metric(item.metrics,"reach","views","plays")??"—"}</td><td>{metric(item.metrics,"likes")??"—"}</td><td>{metric(item.metrics,"comments")??"—"}</td><td>{metric(item.metrics,"saved")??"—"}</td><td>{metric(item.metrics,"shares")??"—"}</td></tr>)}</tbody></table></div>:<div className={styles.empty}>Henüz yeterli medya insights verisi yok.</div>}</section>
    <div className={styles.grid}><section className={styles.panel}><div className={styles.panelHead}><div><span className={styles.eyebrow}>EN İYİ YAYIN SAATLERİ</span><h2>Saat bazlı ortalama</h2></div></div>{hours.length?hours.map((item)=><p className={styles.message} key={item.hour}>{String(item.hour).padStart(2,"0")}:00 · ortalama {item.average} · {item.count} örnek</p>):<div className={styles.empty}>Henüz yeterli veri yok.</div>}</section>
      <section className={styles.panel}><div className={styles.panelHead}><div><span className={styles.eyebrow}>İÇERİK KATEGORİLERİ</span><h2>Kategori performansı</h2></div></div>{categories.length?categories.map((item)=><p className={styles.message} key={item.name}>{item.name} · ortalama {item.average} · {item.count} örnek</p>):<div className={styles.empty}>Henüz yeterli veri yok.</div>}</section></div>
    <section className={styles.panel}><div className={styles.panelHead}><div><span className={styles.eyebrow}>KURAL TABANLI ÖNERİLER</span><h2>Gerçek veriden çıkan notlar</h2></div></div><div className={styles.recommendations}>{recommendations.length?recommendations.map((item)=><p key={item}>{item}</p>):<div className={styles.empty}>Öneri üretmek için henüz yeterli örnek yok.</div>}</div></section>
  </div></main>;
}
